[package]
name = "ruffbox-scheduler"
version = "0.1.0"
authors = ["Niklas <nik@parkellipsen.de>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2"
stdweb = "0.4.17"

[dependencies.web-sys]
version = "0.3"
features = [
  "console",
]
