[package]
name = "ruffbox-pattern"
version = "1.0.0"
authors = ["Niklas <nik@parkellipsen.de>"]
edition = "2018"
license = "GPL-3.0+"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2"
stdweb = "0.4.17"
js-sys = "0.3.0"

[dependencies.web-sys]
version = "0.3"
features = [
  "console",
]
